### ISSUE TITLE
Erreur 500 après authentification

### ISSUE THREAD

**Issue by niko95** [UAPV/RdvZ#21]
Bonjour,

Après l'authentification, j'ai droit à une erreur 500, et la ligne suivante dans mes logs apache :

 Could not parse dsn, referer: http://rdv.blabla.com/meeting

Pour info j'utilise une base mysql pour l'authentification dans laquelle j'ai rajouté un utilisateur manuellement.

En attendant votre aide,
Bien cordialement,

**Comment by ArnaudD** [comment]
Bonjour,

Pourriez vous vérifier le fichier config/databases.yml, il y a peut être une faute de frappe. Le notre ressemble à ça part exemple :

```
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=rdvz'
      username: rdvz
      password: XXXXXXXX
```

**Comment by zorel** [comment]
Bonjour, j'ai le même problème. Mon database.yml

```
all:
  doctrine:
     class: sfDoctrineDatabase
     param:
        dsn: 'mysql:host=localhost;dbname=rdvz'
        username: euro
        password: xxx
```

A noter que lors de l'install, la valeur de host= n'est pas renseignée, on a donc host=;dbname=rdvz, que la migration est bien créée dedans à la valeur 7, et que l'utilisateur par défaut n'est pas créé.

**Comment by zorel** [comment]
Testé avec sqlite.

Le database.yml:

```
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite:host=;dbname=rdvz'
      username: root
      password: null
```

Et je me retrouve avec un fichier host=;dbname=rdvz dans le répertoire de l'application (qui contient config/ et apps/)

J'ai bien la migration_version avec une colonne à 7, mais la table user est vide. Même utilisateur créé, même erreur: could not parse dsn.

Merci.
